### ISSUE TITLE
help

### ISSUE THREAD

**Issue by arifintajul4** [matheeshapathirana/Netflix-cookie-checker#28]
<img width="1196" alt="Screenshot 2023-12-31 at 00 01 51" src="https://github.com/matheeshapathirana/Netflix-cookie-checker/assets/36062540/7d7f167f-75e7-412d-b303-50c9d5aff92a">
help me, problem in mac os sonoma python3

**Comment by matheeshapathirana** [comment]
Try creating a venv and run the program

**Comment by matheeshapathirana** [comment]
I have fixed the issue
