### ISSUE TITLE
invalid cookie domain: Cookie 'domain' mismatch

### ISSUE THREAD

**Issue by VietDuc19** [matheeshapathirana/Netflix-cookie-checker#29]
I got the following error when checking:
Error occurred: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome-headless-shell=120.0.6099.109)
Stacktrace:
#0 0x58f35373af83 <unknown>
#1 0x58f3533f3cf7 <unknown>
#2 0x58f3534a0538 <unknown>
#3 0x58f35346d0b2 <unknown>
#4 0x58f35348c006 <unknown>
#5 0x58f35346ce53 <unknown>
#6 0x58f353434dd4 <unknown>
#7 0x58f3534361de <unknown>
#8 0x58f3536ff531 <unknown>
#9 0x58f353703455 <unknown>
#10 0x58f3536ebf55 <unknown>
#11 0x58f3537040ef <unknown>
#12 0x58f3536cf99f <unknown>
#13 0x58f353728008 <unknown>
#14 0x58f3537281d7 <unknown>
#15 0x58f35373a124 <unknown>
#16 0x7a1d80a66ac3 <unknown>
- [Standart - Standard] [abcxyz@gmail.com].txt
But this cookie is still working. Please help me to check.

**Comment by matheeshapathirana** [comment]
can you please send me that cookie

**Comment by VietDuc19** [comment]
How can I send it to you? I can not public it.

**Comment by matheeshapathirana** [comment]
You can join our discord server and open a ticket

https://discord.gg/RSCdKeKB5X

**Comment by VietDuc19** [comment]
Hi @matheeshapathirana 
I joined the discord channel and opened the ticket.
Thank you so much for your help.
