### ISSUE TITLE
Too slow!

### ISSUE THREAD

**Issue by Nuhash3303** [matheeshapathirana/Netflix-cookie-checker#32]
Hey can you make it faster? It takes a lot of time to check. Also if you can make a same checker for primevideo, Spotify I'll be great!

**Comment by matheeshapathirana** [comment]
Speed depends on your network speed, if you have a slow internet connection we recommend you to use the [colab version](https://github.com/matheeshapathirana/Netflix-cookie-checker/tree/colab-version).
