### ISSUE TITLE
Fake hits

### ISSUE THREAD

**Issue by Myztical1** [matheeshapathirana/Netflix-cookie-checker#33]
The main.py script hitting invalid cookies & printing working. Please revise script to hit only valid cookies only as working.Thanks

**Comment by matheeshapathirana** [comment]
Can you please send me that cookie. you can join our [discord server](https://discord.gg/RSCdKeKB5X) and create a ticket

**Comment by Myztical1** [comment]
Some saying working but it's not

**Comment by matheeshapathirana** [comment]
Make sure you are using the latest version. we have already fixed this issue in a previous commit.

**Comment by Myztical1** [comment]
> Make sure you are using the latest version. we have already fixed this issue in a previous commit.

Did you test cookies sent to verify your claim ?
