### ISSUE TITLE
format of cookies

### ISSUE THREAD

**Issue by beautiful260** [matheeshapathirana/Netflix-cookie-checker#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by beautiful260** [comment]
i want to know that in what format and with what file extensions we nwwd to upload these cookies

**Comment by matheeshapathirana** [comment]
If you have netscape format cookies, convert them to json format using the `cookie_converter.py`. If you already have json cookies, paste them inside `json_cookies` folder
