### ISSUE TITLE
Looks great project, but form where i can find cookies collection?

### ISSUE THREAD

**Issue by yesbhautik** [matheeshapathirana/Netflix-cookie-checker#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matheeshapathirana** [comment]
There are many websites and telegram channels/groups uploading cookies. Join some to get cookies

**Comment by yesbhautik** [comment]
can you share it with me? if yes then please send on telegram @yesbhautik or email hi@yesbhautik.co.in
