### ISSUE TITLE
Cannot connect to host www.netflix.com:443 ssl:default [None] 

### ISSUE THREAD

**Issue by kevinmf1** [matheeshapathirana/Netflix-cookie-checker#61]
i got this error when i tried to run the code via google colab. any solution?

![image](https://github.com/matheeshapathirana/Netflix-cookie-checker/assets/97342935/900698e2-a10c-4839-823d-0a51262cc7d1)

**Comment by matheeshapathirana** [comment]
Please lower the thread count.
