### ISSUE TITLE
Seems there is glitch 

### ISSUE THREAD

**Issue by xylozd** [matheeshapathirana/Netflix-cookie-checker#8]
I have working cookie, from which I m able to log in to my web browser.

But somehow when i check this with this cookie checker, I always get following error

Invalid Cookie or webdriver error - 

Cookie is valid but not sure why it shows this.

I made some required changes in folder path to get it run in colab.

Thanks

**Comment by matheeshapathirana** [comment]
Yeah it's a problem with the webdriver, if the cookie is not working you will get the output 'cookie not working'. Soon I will test this with chromedriver. So, please be patient

**Comment by matheeshapathirana** [comment]
Try this https://github.com/matheeshapathirana/Netflix-cookie-checker/tree/colab-version. I have fixed the issues, now it works fine.
